/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as PlataformaRouteImport } from './routes/plataforma'
import { Route as RecuperarSenhaRouteImport } from './routes/recuperar-senha'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppAgendaRouteImport } from './routes/app/agenda'
import { Route as AppAssinaturaRouteImport } from './routes/app/assinatura'
import { Route as AppAuditoriaRouteImport } from './routes/app/auditoria'
import { Route as AppAutomacoesRouteImport } from './routes/app/automacoes'
import { Route as AppCampanhasRouteImport } from './routes/app/campanhas'
import { Route as AppClientesRouteImport } from './routes/app/clientes'
import { Route as AppConfiguracoesRouteImport } from './routes/app/configuracoes'
import { Route as AppDinheiroPerdidoRouteImport } from './routes/app/dinheiro-perdido'
import { Route as AppEquipeRouteImport } from './routes/app/equipe'
import { Route as AppFidelidadeRouteImport } from './routes/app/fidelidade'
import { Route as AppFinanceiroRouteImport } from './routes/app/financeiro'
import { Route as AppFunilRouteImport } from './routes/app/funil'
import { Route as AppIaRouteImport } from './routes/app/ia'
import { Route as AppLeadsRouteImport } from './routes/app/leads'
import { Route as AppNotificacoesRouteImport } from './routes/app/notificacoes'
import { Route as AppOrcamentosRouteImport } from './routes/app/orcamentos'
import { Route as AppProdutosRouteImport } from './routes/app/produtos'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AppCampanhasIdRouteImport } from './routes/app/campanhas.$id'
import { Route as AppClientesIdRouteImport } from './routes/app/clientes.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PlataformaRoute = PlataformaRouteImport.update({
  id: '/plataforma',
  path: '/plataforma',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarSenhaRoute = RecuperarSenhaRouteImport.update({
  id: '/recuperar-senha',
  path: '/recuperar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAgendaRoute = AppAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAssinaturaRoute = AppAssinaturaRouteImport.update({
  id: '/assinatura',
  path: '/assinatura',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAuditoriaRoute = AppAuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAutomacoesRoute = AppAutomacoesRouteImport.update({
  id: '/automacoes',
  path: '/automacoes',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCampanhasRoute = AppCampanhasRouteImport.update({
  id: '/campanhas',
  path: '/campanhas',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppClientesRoute = AppClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppConfiguracoesRoute = AppConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDinheiroPerdidoRoute = AppDinheiroPerdidoRouteImport.update({
  id: '/dinheiro-perdido',
  path: '/dinheiro-perdido',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppEquipeRoute = AppEquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppFidelidadeRoute = AppFidelidadeRouteImport.update({
  id: '/fidelidade',
  path: '/fidelidade',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppFinanceiroRoute = AppFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppFunilRoute = AppFunilRouteImport.update({
  id: '/funil',
  path: '/funil',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppIaRoute = AppIaRouteImport.update({
  id: '/ia',
  path: '/ia',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppLeadsRoute = AppLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppNotificacoesRoute = AppNotificacoesRouteImport.update({
  id: '/notificacoes',
  path: '/notificacoes',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppOrcamentosRoute = AppOrcamentosRouteImport.update({
  id: '/orcamentos',
  path: '/orcamentos',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProdutosRoute = AppProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => AppRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCampanhasIdRoute = AppCampanhasIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppCampanhasRoute,
} as any)
const AppClientesIdRoute = AppClientesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppClientesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/plataforma': typeof PlataformaRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/app/agenda': typeof AppAgendaRoute
  '/app/assinatura': typeof AppAssinaturaRoute
  '/app/auditoria': typeof AppAuditoriaRoute
  '/app/automacoes': typeof AppAutomacoesRoute
  '/app/campanhas': typeof AppCampanhasRouteWithChildren
  '/app/clientes': typeof AppClientesRouteWithChildren
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/dinheiro-perdido': typeof AppDinheiroPerdidoRoute
  '/app/equipe': typeof AppEquipeRoute
  '/app/fidelidade': typeof AppFidelidadeRoute
  '/app/financeiro': typeof AppFinanceiroRoute
  '/app/funil': typeof AppFunilRoute
  '/app/ia': typeof AppIaRoute
  '/app/leads': typeof AppLeadsRoute
  '/app/notificacoes': typeof AppNotificacoesRoute
  '/app/orcamentos': typeof AppOrcamentosRoute
  '/app/produtos': typeof AppProdutosRoute
  '/app/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/campanhas/$id': typeof AppCampanhasIdRoute
  '/app/clientes/$id': typeof AppClientesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/plataforma': typeof PlataformaRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/app/agenda': typeof AppAgendaRoute
  '/app/assinatura': typeof AppAssinaturaRoute
  '/app/auditoria': typeof AppAuditoriaRoute
  '/app/automacoes': typeof AppAutomacoesRoute
  '/app/campanhas': typeof AppCampanhasRouteWithChildren
  '/app/clientes': typeof AppClientesRouteWithChildren
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/dinheiro-perdido': typeof AppDinheiroPerdidoRoute
  '/app/equipe': typeof AppEquipeRoute
  '/app/fidelidade': typeof AppFidelidadeRoute
  '/app/financeiro': typeof AppFinanceiroRoute
  '/app/funil': typeof AppFunilRoute
  '/app/ia': typeof AppIaRoute
  '/app/leads': typeof AppLeadsRoute
  '/app/notificacoes': typeof AppNotificacoesRoute
  '/app/orcamentos': typeof AppOrcamentosRoute
  '/app/produtos': typeof AppProdutosRoute
  '/app': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/campanhas/$id': typeof AppCampanhasIdRoute
  '/app/clientes/$id': typeof AppClientesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/plataforma': typeof PlataformaRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/app/agenda': typeof AppAgendaRoute
  '/app/assinatura': typeof AppAssinaturaRoute
  '/app/auditoria': typeof AppAuditoriaRoute
  '/app/automacoes': typeof AppAutomacoesRoute
  '/app/campanhas': typeof AppCampanhasRouteWithChildren
  '/app/clientes': typeof AppClientesRouteWithChildren
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/dinheiro-perdido': typeof AppDinheiroPerdidoRoute
  '/app/equipe': typeof AppEquipeRoute
  '/app/fidelidade': typeof AppFidelidadeRoute
  '/app/financeiro': typeof AppFinanceiroRoute
  '/app/funil': typeof AppFunilRoute
  '/app/ia': typeof AppIaRoute
  '/app/leads': typeof AppLeadsRoute
  '/app/notificacoes': typeof AppNotificacoesRoute
  '/app/orcamentos': typeof AppOrcamentosRoute
  '/app/produtos': typeof AppProdutosRoute
  '/app/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/campanhas/$id': typeof AppCampanhasIdRoute
  '/app/clientes/$id': typeof AppClientesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/cadastro'
    | '/login'
    | '/onboarding'
    | '/plataforma'
    | '/recuperar-senha'
    | '/app/agenda'
    | '/app/assinatura'
    | '/app/auditoria'
    | '/app/automacoes'
    | '/app/campanhas'
    | '/app/clientes'
    | '/app/configuracoes'
    | '/app/dinheiro-perdido'
    | '/app/equipe'
    | '/app/fidelidade'
    | '/app/financeiro'
    | '/app/funil'
    | '/app/ia'
    | '/app/leads'
    | '/app/notificacoes'
    | '/app/orcamentos'
    | '/app/produtos'
    | '/app/'
    | '/api/auth/$'
    | '/app/campanhas/$id'
    | '/app/clientes/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cadastro'
    | '/login'
    | '/onboarding'
    | '/plataforma'
    | '/recuperar-senha'
    | '/app/agenda'
    | '/app/assinatura'
    | '/app/auditoria'
    | '/app/automacoes'
    | '/app/campanhas'
    | '/app/clientes'
    | '/app/configuracoes'
    | '/app/dinheiro-perdido'
    | '/app/equipe'
    | '/app/fidelidade'
    | '/app/financeiro'
    | '/app/funil'
    | '/app/ia'
    | '/app/leads'
    | '/app/notificacoes'
    | '/app/orcamentos'
    | '/app/produtos'
    | '/app'
    | '/api/auth/$'
    | '/app/campanhas/$id'
    | '/app/clientes/$id'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/cadastro'
    | '/login'
    | '/onboarding'
    | '/plataforma'
    | '/recuperar-senha'
    | '/app/agenda'
    | '/app/assinatura'
    | '/app/auditoria'
    | '/app/automacoes'
    | '/app/campanhas'
    | '/app/clientes'
    | '/app/configuracoes'
    | '/app/dinheiro-perdido'
    | '/app/equipe'
    | '/app/fidelidade'
    | '/app/financeiro'
    | '/app/funil'
    | '/app/ia'
    | '/app/leads'
    | '/app/notificacoes'
    | '/app/orcamentos'
    | '/app/produtos'
    | '/app/'
    | '/api/auth/$'
    | '/app/campanhas/$id'
    | '/app/clientes/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  CadastroRoute: typeof CadastroRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  PlataformaRoute: typeof PlataformaRoute
  RecuperarSenhaRoute: typeof RecuperarSenhaRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plataforma': {
      id: '/plataforma'
      path: '/plataforma'
      fullPath: '/plataforma'
      preLoaderRoute: typeof PlataformaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperar-senha': {
      id: '/recuperar-senha'
      path: '/recuperar-senha'
      fullPath: '/recuperar-senha'
      preLoaderRoute: typeof RecuperarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/agenda': {
      id: '/app/agenda'
      path: '/agenda'
      fullPath: '/app/agenda'
      preLoaderRoute: typeof AppAgendaRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/assinatura': {
      id: '/app/assinatura'
      path: '/assinatura'
      fullPath: '/app/assinatura'
      preLoaderRoute: typeof AppAssinaturaRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/auditoria': {
      id: '/app/auditoria'
      path: '/auditoria'
      fullPath: '/app/auditoria'
      preLoaderRoute: typeof AppAuditoriaRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/automacoes': {
      id: '/app/automacoes'
      path: '/automacoes'
      fullPath: '/app/automacoes'
      preLoaderRoute: typeof AppAutomacoesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/campanhas': {
      id: '/app/campanhas'
      path: '/campanhas'
      fullPath: '/app/campanhas'
      preLoaderRoute: typeof AppCampanhasRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/clientes': {
      id: '/app/clientes'
      path: '/clientes'
      fullPath: '/app/clientes'
      preLoaderRoute: typeof AppClientesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/configuracoes': {
      id: '/app/configuracoes'
      path: '/configuracoes'
      fullPath: '/app/configuracoes'
      preLoaderRoute: typeof AppConfiguracoesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/dinheiro-perdido': {
      id: '/app/dinheiro-perdido'
      path: '/dinheiro-perdido'
      fullPath: '/app/dinheiro-perdido'
      preLoaderRoute: typeof AppDinheiroPerdidoRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/equipe': {
      id: '/app/equipe'
      path: '/equipe'
      fullPath: '/app/equipe'
      preLoaderRoute: typeof AppEquipeRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/fidelidade': {
      id: '/app/fidelidade'
      path: '/fidelidade'
      fullPath: '/app/fidelidade'
      preLoaderRoute: typeof AppFidelidadeRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/financeiro': {
      id: '/app/financeiro'
      path: '/financeiro'
      fullPath: '/app/financeiro'
      preLoaderRoute: typeof AppFinanceiroRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/funil': {
      id: '/app/funil'
      path: '/funil'
      fullPath: '/app/funil'
      preLoaderRoute: typeof AppFunilRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/ia': {
      id: '/app/ia'
      path: '/ia'
      fullPath: '/app/ia'
      preLoaderRoute: typeof AppIaRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/leads': {
      id: '/app/leads'
      path: '/leads'
      fullPath: '/app/leads'
      preLoaderRoute: typeof AppLeadsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/notificacoes': {
      id: '/app/notificacoes'
      path: '/notificacoes'
      fullPath: '/app/notificacoes'
      preLoaderRoute: typeof AppNotificacoesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/orcamentos': {
      id: '/app/orcamentos'
      path: '/orcamentos'
      fullPath: '/app/orcamentos'
      preLoaderRoute: typeof AppOrcamentosRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/produtos': {
      id: '/app/produtos'
      path: '/produtos'
      fullPath: '/app/produtos'
      preLoaderRoute: typeof AppProdutosRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/campanhas/$id': {
      id: '/app/campanhas/$id'
      path: '/$id'
      fullPath: '/app/campanhas/$id'
      preLoaderRoute: typeof AppCampanhasIdRouteImport
      parentRoute: typeof AppCampanhasRoute
    }
    '/app/clientes/$id': {
      id: '/app/clientes/$id'
      path: '/$id'
      fullPath: '/app/clientes/$id'
      preLoaderRoute: typeof AppClientesIdRouteImport
      parentRoute: typeof AppClientesRoute
    }
  }
}

interface AppCampanhasRouteChildren {
  AppCampanhasIdRoute: typeof AppCampanhasIdRoute
}

const AppCampanhasRouteChildren: AppCampanhasRouteChildren = {
  AppCampanhasIdRoute: AppCampanhasIdRoute,
}

const AppCampanhasRouteWithChildren = AppCampanhasRoute._addFileChildren(
  AppCampanhasRouteChildren,
)

interface AppClientesRouteChildren {
  AppClientesIdRoute: typeof AppClientesIdRoute
}

const AppClientesRouteChildren: AppClientesRouteChildren = {
  AppClientesIdRoute: AppClientesIdRoute,
}

const AppClientesRouteWithChildren = AppClientesRoute._addFileChildren(
  AppClientesRouteChildren,
)

interface AppRouteRouteChildren {
  AppAgendaRoute: typeof AppAgendaRoute
  AppAssinaturaRoute: typeof AppAssinaturaRoute
  AppAuditoriaRoute: typeof AppAuditoriaRoute
  AppAutomacoesRoute: typeof AppAutomacoesRoute
  AppCampanhasRoute: typeof AppCampanhasRouteWithChildren
  AppClientesRoute: typeof AppClientesRouteWithChildren
  AppConfiguracoesRoute: typeof AppConfiguracoesRoute
  AppDinheiroPerdidoRoute: typeof AppDinheiroPerdidoRoute
  AppEquipeRoute: typeof AppEquipeRoute
  AppFidelidadeRoute: typeof AppFidelidadeRoute
  AppFinanceiroRoute: typeof AppFinanceiroRoute
  AppFunilRoute: typeof AppFunilRoute
  AppIaRoute: typeof AppIaRoute
  AppLeadsRoute: typeof AppLeadsRoute
  AppNotificacoesRoute: typeof AppNotificacoesRoute
  AppOrcamentosRoute: typeof AppOrcamentosRoute
  AppProdutosRoute: typeof AppProdutosRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppAgendaRoute: AppAgendaRoute,
  AppAssinaturaRoute: AppAssinaturaRoute,
  AppAuditoriaRoute: AppAuditoriaRoute,
  AppAutomacoesRoute: AppAutomacoesRoute,
  AppCampanhasRoute: AppCampanhasRouteWithChildren,
  AppClientesRoute: AppClientesRouteWithChildren,
  AppConfiguracoesRoute: AppConfiguracoesRoute,
  AppDinheiroPerdidoRoute: AppDinheiroPerdidoRoute,
  AppEquipeRoute: AppEquipeRoute,
  AppFidelidadeRoute: AppFidelidadeRoute,
  AppFinanceiroRoute: AppFinanceiroRoute,
  AppFunilRoute: AppFunilRoute,
  AppIaRoute: AppIaRoute,
  AppLeadsRoute: AppLeadsRoute,
  AppNotificacoesRoute: AppNotificacoesRoute,
  AppOrcamentosRoute: AppOrcamentosRoute,
  AppProdutosRoute: AppProdutosRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  CadastroRoute: CadastroRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  PlataformaRoute: PlataformaRoute,
  RecuperarSenhaRoute: RecuperarSenhaRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
